name: Go CI Pipeline

on: [push, pull_request]  # Run on every push or PR.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22  # Specify your Go version

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: 
          go test -v ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out

      - name: Build Binary
        run: go build -o futil ./cmd/main.go

      - name: Generate JUnit report
        run: go test -v ./... | go-junit-report > report.xml

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out

      - name: Display coverage
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v3
        with:
          name: html-coverage-report
          path: coverage.html
