name: Go CI Pipeline

on: [push, pull_request]  # Run on every push or PR.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22  # Specify your Go version

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-mod-${{ runner.os }}-

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./... -v

      - name: Build Binary
        run: go build -o futil ./cmd/main.go
